name: Waka Readme Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily at 12 AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # Step to update README with WakaTime metrics
      - name: WakaTime Metrics Update
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          
          # Meta Configuration
          API_BASE_URL: https://wakatime.com/api # default API URL format
          
          # Content Configuration
          SHOW_TITLE: true # add title to waka-readme section in README
          SECTION_NAME: waka # custom section header for stats
          BLOCKS: ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ # fancier ASCII art for stats graph
          CODE_LANG: txt # syntax highlighting for stats content
          TIME_RANGE: last_7_days # set time range for stats (last 7 days)
          LANG_COUNT: 5 # display top 5 languages
          SHOW_TIME: true # display time spent per language/activity
          SHOW_TOTAL: true # show total coding time
          SHOW_MASKED_TIME: false # disable masked time including unclassified languages
          STOP_AT_OTHER: true # stop listing when "Other" is reached in languages
          IGNORED_LANGUAGES: YAML JSON TOML # ignore specific languages

          # Commit Configuration
          COMMIT_MESSAGE: "Update waka-readme metrics for VSCode activity"
          TARGET_BRANCH: main # use 'main' branch if applicable
          TARGET_PATH: README.md # target README file
          COMMITTER_NAME: "GitHub Action Bot"
          COMMITTER_EMAIL: "action-bot@github.com"
          AUTHOR_NAME: "Claudio Rea"
          AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }} # set email in GitHub secrets for privacy
