name: Waka Readme Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily at 12 AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # Step to update README with WakaTime metrics
      - name: WakaTime Metrics Update
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          
          # Meta Configuration
          API_BASE_URL: https://wakatime.com/api # default API URL format
          
          # Content Configuration
          SHOW_TITLE: true
          SECTION_NAME: waka # custom section header
          BLOCKS: -> # collapsible sections in the report
          CODE_LANG: vscode # specifically for metrics related to VSCode usage
          TIME_RANGE: last_7_days # shows data from the past week
          LANG_COUNT: 5 # limit to top 5 languages for a concise summary
          SHOW_TIME: true # display time spent per language or activity
          SHOW_TOTAL: true # show the overall time spent on VSCode
          STOP_AT_OTHER: true # stop at "Other" section
          IGNORED_LANGUAGES: YAML JSON TOML # ignore these languages
          
          STOP_AT_OTHER: true # stop at "Other" section
          IGNORED_LANGUAGES: YAML JSON TOML # ignore these languages

          # Commit Configuration
          COMMIT_MESSAGE: "Update waka-readme metrics for VSCode activity"
          TARGET_BRANCH: main # use 'main' branch if applicable
          TARGET_PATH: README.md # target README file
          COMMITTER_NAME: "GitHub Action Bot"
          COMMITTER_EMAIL: "action-bot@github.com"
          AUTHOR_NAME: "Claudio Rea"
          AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }} # set email in GitHub secrets for privacy
